version: '3.8'

services:
  api:
    container_name: api
    build: .
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy
        restart: true

    environment:
      JOURNEY_DATABASE_USER: ${JOURNEY_DATABASE_USER}
      JOURNEY_DATABASE_PASSWORD: ${JOURNEY_DATABASE_PASSWORD}
      JOURNEY_DATABASE_HOST: ${JOURNEY_DATABASE_HOST}
      JOURNEY_DATABASE_PORT: ${JOURNEY_DATABASE_PORT}
      JOURNEY_DATABASE_NAME: ${JOURNEY_DATABASE_NAME}
    networks:
      - journey

  postgres:
    image: postgres:16.2-alpine3.19
    container_name: api-db
    ports:
      - ${JOURNEY_DATABASE_PORT}:5432
    environment:
      POSTGRES_USER: ${JOURNEY_DATABASE_USER}
      POSTGRES_PASSWORD: ${JOURNEY_DATABASE_PASSWORD}
      POSTGRES_DB: ${JOURNEY_DATABASE_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${JORUNEY_DATABASE_USER} -d ${JOURNEY_DATABASE_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - journey

networks:
  journey:
    driver: bridge